InMAPData="geos-chem/inmap_inputs_geoschem4x5.ncf"

[Preproc]
  CTMType="GEOS-Chem"

  CtmGridDx=5
  CtmGridDy=4

  CtmGridXo=-180
  CtmGridYo=-90

  StartDate="20130101"
  #EndDate="20140101"
  EndDate="20130310" # We only process first 3 months because of 'Invalid CDF magic' error

  [Preproc.GEOSChem]
    GEOSA1="D:/geos-chem/geosfp/GEOSFP.[DATE].A1.4x5.nc"
    GEOSA3Cld="D:/geos-chem/geosfp/GEOSFP.[DATE].A3cld.4x5.nc"
    GEOSA3Dyn="D:/geos-chem/geosfp/GEOSFP.[DATE].A3dyn.4x5.nc"
    GEOSA3MstE="D:/geos-chem/geosfp/GEOSFP.[DATE].A3mstE.4x5.nc"
    GEOSI3="D:/geos-chem/geosfp/GEOSFP.[DATE].I3.4x5.nc"
    GEOSApBp="D:/geos-chem/GEOSFP.ApBp.nc"

    GEOSChem="C:/Users/Chris/Documents/data/geos-chem/chem/v11-02c-Run0.[DATE].nc"

    VegTypeGlobal="geos-chem/vegtype.global"
